
name: "Image Build and Publish Job"
on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Build and push image
              run: |
                docker login --username ckroeger --password ${{ secrets.IMAGE_PUSH_TOKEN }} ghcr.io
                docker build -t ghcr.io/ckroeger/hello:latest .
                docker push ghcr.io/ckroeger/hello:latest